url: "" # the base hostname & protocol for your site, e.g. http://example.com

title: Puzzle Schnuppertag 2020
email: info@puzzle.ch #this is also the email contact forms will go to
description: "Puzzle ITC Schnuppertag 08. Oktober 2020"
author: Puzzle ITC
markdown: kramdown
